name: reserved-slots
main: org.powernukkit.plugins.reservedslots.ReservedSlotsPlugin
version: "${project.version}"
api: ["1.0.12"]

author: JoseRobJR
description: Reserve player slots for important players

website: https://github.com/PowerNukkit/Plugin-Reserved-Slots

softdepend:
  - PowerNukkit

#commands:
#  cloneme:
#    description: Example command
#
#    usage: "/example"
#    
#    permission: cloneme.cmd.use
    
permissions:
  reservedslots.notaffected:
    description: Players with this permission aren't affected by this plugin, regardless of others permissions.
    default: false
  reservedslots.joinfull:
    description: Allows the player to join even if the server is completely full
    default: op
