# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Update site

on:
  push:
    branches:
      - master

jobs:
  update-site:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout main code
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate site
      run: mvn -B site -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - uses: actions/checkout@v2
      name: Checkout last site
      with:
        path: site
        ref: site
    - name: Prepare the site branch
      run: |
        cd site
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout site
    - name: Update site
      run: |
        rm -rf site/*
        cp -a target/site/* site/
    - name: Add Google Analytics code snippet
      run: find site/ -type f -exec sed -ri 's/^<head>$/\<head\/\>\<\!\-\- Global site tag \(gtag\.js\) \- Google Analytics \-\-\> \<script async src\="https\:\/\/www\.googletagmanager\.com\/gtag\/js\?id\=UA\-172727144\-3"\>\<\/script\> \<script\> window\.dataLayer \= window\.dataLayer \|\| \[\]; function gtag\(\)\{dataLayer\.push\(arguments\);\} gtag\("js", new Date\(\)\); gtag\("config", "UA\-172727144\-3"\); \<\/script\>/g' {} \;
    - uses: actions/setup-node@v1
      name: Install NPM
      with:
          node-version: 12
    - name: Install sitemap-static
      run: npm install -g sitemap-static
    - name: Generate sitemap.xml
      run: sitemap-static --pretty --prefix=https://powernukkit.github.io/ site > site/sitemap.xml
    - name: Commit the updated site
      run: |
        cd site
        git config --local user.email "github-bot@powernukkit.org"
        git config --local user.name "PowerNukkit Bot"
        git add sitemap.xml
        git add -A ./
        if [ ! -z "$(git status --porcelain)" ]; then
          git commit -m "Update the plugin site"
          git push
        fi
